use_frameworks!

platform :ios, '9.0'

target 'ShoPiaoPiao_Example' do
  pod 'ShoPiaoPiao', :path => '../'

  target 'ShoPiaoPiao_Tests' do
    inherit! :search_paths

#    pod 'Specta'
#    pod 'Expecta'
#    pod 'FBSnapshotTestCase'
#    pod 'Expecta+Snapshots'
    pod 'Masonry'
    pod 'AFNetworking'
    pod 'SDWebImage'
    pod 'YYModel'
  end
end
