use_frameworks!

platform :ios, '9.0'

target 'ShoPiaoPiao_Example' do
  pod 'ShoPiaoPiao', :path => '../'
  
  pod 'Masonry'
  pod 'AFNetworking'
  pod 'SDWebImage'
  pod 'YYModel'
  pod 'MJRefresh'

  target 'ShoPiaoPiao_Tests' do
    inherit! :search_paths
#    pod 'Specta'
#    pod 'Expecta'
#    pod 'FBSnapshotTestCase'
#    pod 'Expecta+Snapshots'
  end
  
end
